export const GET_SEARCH_RESULT_STARTING = 'GET_SEARCH_RESULT_STARTING';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_ERROR = 'GET_SEARCH_RESULT_ERROR';

export const SAVE_SEARCH_RESULT_STARTING = 'SAVE_SEARCH_RESULT_STARTING';
export const SAVE_SEARCH_RESULT_SUCCESS = 'SAVE_SEARCH_RESULT_SUCCESS';
export const SAVE_SEARCH_RESULT_ERROR = 'SAVE_SEARCH_RESULT_ERROR';

export const GET_SEARCH_SUGGESTIONS_STARTING= 'GET_SEARCH_SUGGESTIONS_STARTING';
export const GET_SEARCH_SUGGESTIONS_SUCCESS = 'GET_SEARCH_SUGGESTIONS_SUCCESS';
export const GET_SEARCH_SUGGESTIONS_ERROR = 'GET_SEARCH_SUGGESTIONS_ERROR';
export const SET_SELECTED_SUGGESTION = 'SET_SELECTED_SUGGESTION';

export const GET_APP_CONFIG_STARTING = 'GET_APP_CONFIG_STARTING';
export const GET_APP_CONFIG_SUCCESS = 'GET_APP_CONFIG_SUCCESS';
export const GET_APP_CONFIG_ERROR = 'GET_APP_CONFIG_ERROR';

export const SAVE_APP_CONFIG_STARTING = 'SAVE_APP_CONFIG_STARTING';
export const SAVE_APP_CONFIG_SUCCESS = 'SAVE_APP_CONFIG_SUCCESS';
export const SAVE_APP_CONFIG_ERROR = 'SAVE_APP_CONFIG_ERROR';

export const FILE_UPLOAD_STARTING = 'FILE_UPLOAD_STARTING';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';

export const GET_AUTH_TOKENS_STARTING = 'GET_AUTH_TOKENS_STARTING';
export const GET_AUTH_TOKENS_SUCCESS = 'GET_AUTH_TOKENS_SUCCESS';
export const GET_AUTH_TOKENS_ERROR = 'GET_AUTH_TOKENS_ERROR';

export const CREATE_AUTH_TOKEN_STARTING = 'CREATE_AUTH_TOKEN_STARTING';
export const CREATE_AUTH_TOKEN_SUCCESS = 'CREATE_AUTH_TOKEN_SUCCESS';
export const CREATE_AUTH_TOKEN_ERROR = 'CREATE_AUTH_TOKEN_ERROR';

export const UPDATE_AUTH_TOKEN_STARTING = 'UPDATE_AUTH_TOKEN_STARTING';
export const UPDATE_AUTH_TOKEN_SUCCESS = 'UPDATE_AUTH_TOKEN_SUCCESS';
export const UPDATE_AUTH_TOKEN_ERROR = 'UPDATE_AUTH_TOKEN_ERROR';

export const DELETE_AUTH_TOKEN_STARTING = 'DELETE_AUTH_TOKEN_STARTING';
export const DELETE_AUTH_TOKEN_SUCCESS = 'DELETE_AUTH_TOKEN_SUCCESS';
export const DELETE_AUTH_TOKEN_ERROR = 'DELETE_AUTH_TOKEN_ERROR';
